spring.application.name=api-gateway
server.port=8080

spring.cloude.gateway.discovery.locator.enabled=true 
spring.cloude.gateway.discovery.locator.lowercase-service-id=true

# --- ACTUATOR CONFIGURATION ---
# Expose the health and info endpoints over HTTP
management.endpoints.web.exposure.include=health,info,metrics
# Show detailed health status (e.g., database connection status)
management.endpoint.health.show-details=always

# --- LOGGING CONFIGURATION ---
# Default log level for the whole application
logging.level.root=INFO
# Show detailed debug logs only for your specific code (change the package name accordingly)
logging.level.com.ridelink=DEBUG