spring.config.import=optional:classpath:env.properties

spring.application.name=ride-service
server.port=8083

# Database Configuration
spring.datasource.url=${RIDE_DB_HOST}
spring.datasource.username=${RIDE_DB_USER}
spring.datasource.password=${RIDE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- ACTUATOR CONFIGURATION ---
# Expose the health and info endpoints over HTTP
management.endpoints.web.exposure.include=health,info,metrics
# Show detailed health status (e.g., database connection status)
management.endpoint.health.show-details=always

# --- LOGGING CONFIGURATION ---
# Default log level for the whole application
logging.level.root=INFO
# Show detailed debug logs only for your specific code (change the package name accordingly)
logging.level.com.ridelink=DEBUG
# Keep Hibernate SQL logs quiet unless there is a problem (show-sql=false, so use DEBUG here to see SQL when needed)
logging.level.org.hibernate.SQL=DEBUG

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch the registry from Eureka
eureka.client.fetch-registry=true